environment: prod
image: quay.io/nordstrom/choices
elwin:
  name: elwin
  readTimeout: 5s
  writeTimeout: 5s
  idleTimeout: 2m
  failTimeout: 15m
  updateInterval: 10s
  metricsPort: 8081
  jsonPort: 8080
mongo:
  name: elwin-mongo
  address: elwin-mongo-v1-mongodb
  user: ""
  password: ""
