// Code generated by protoc-gen-go.
// source: elwin.proto
// DO NOT EDIT!

/*
Package elwin is a generated protocol buffer package.

It is generated from these files:
	elwin.proto

It has these top-level messages:
	Identifier
	Experiments
	Experiment
	Param
*/
package elwin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Identifier struct {
	TeamID string `protobuf:"bytes,1,opt,name=teamID" json:"teamID,omitempty"`
	UserID string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
}

func (m *Identifier) Reset()                    { *m = Identifier{} }
func (m *Identifier) String() string            { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()               {}
func (*Identifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Identifier) GetTeamID() string {
	if m != nil {
		return m.TeamID
	}
	return ""
}

func (m *Identifier) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type Experiments struct {
	Experiments map[string]*Experiment `protobuf:"bytes,1,rep,name=experiments" json:"experiments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Experiments) Reset()                    { *m = Experiments{} }
func (m *Experiments) String() string            { return proto.CompactTextString(m) }
func (*Experiments) ProtoMessage()               {}
func (*Experiments) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Experiments) GetExperiments() map[string]*Experiment {
	if m != nil {
		return m.Experiments
	}
	return nil
}

type Experiment struct {
	Params []*Param `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
}

func (m *Experiment) Reset()                    { *m = Experiment{} }
func (m *Experiment) String() string            { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()               {}
func (*Experiment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Experiment) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type Param struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Param) Reset()                    { *m = Param{} }
func (m *Param) String() string            { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()               {}
func (*Param) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Identifier)(nil), "elwin.Identifier")
	proto.RegisterType((*Experiments)(nil), "elwin.Experiments")
	proto.RegisterType((*Experiment)(nil), "elwin.Experiment")
	proto.RegisterType((*Param)(nil), "elwin.Param")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Elwin service

type ElwinClient interface {
	GetNamespaces(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Experiments, error)
}

type elwinClient struct {
	cc *grpc.ClientConn
}

func NewElwinClient(cc *grpc.ClientConn) ElwinClient {
	return &elwinClient{cc}
}

func (c *elwinClient) GetNamespaces(ctx context.Context, in *Identifier, opts ...grpc.CallOption) (*Experiments, error) {
	out := new(Experiments)
	err := grpc.Invoke(ctx, "/elwin.Elwin/GetNamespaces", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Elwin service

type ElwinServer interface {
	GetNamespaces(context.Context, *Identifier) (*Experiments, error)
}

func RegisterElwinServer(s *grpc.Server, srv ElwinServer) {
	s.RegisterService(&_Elwin_serviceDesc, srv)
}

func _Elwin_GetNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElwinServer).GetNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/elwin.Elwin/GetNamespaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElwinServer).GetNamespaces(ctx, req.(*Identifier))
	}
	return interceptor(ctx, in, info, handler)
}

var _Elwin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "elwin.Elwin",
	HandlerType: (*ElwinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNamespaces",
			Handler:    _Elwin_GetNamespaces_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "elwin.proto",
}

func init() { proto.RegisterFile("elwin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x51, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0x36, 0x9d, 0x2d, 0xec, 0x44, 0x61, 0x1e, 0x44, 0xca, 0xae, 0x46, 0x14, 0xdc, 0xd5, 0xc0,
	0x7a, 0x33, 0xc4, 0x1b, 0x61, 0x45, 0x7a, 0x23, 0xda, 0x37, 0x88, 0x7a, 0x84, 0xe2, 0x92, 0x95,
	0x24, 0x53, 0xf7, 0x44, 0xbe, 0xa6, 0x34, 0x8d, 0x34, 0x6c, 0x77, 0xdf, 0xcf, 0x39, 0xf9, 0x3e,
	0x4e, 0x80, 0xd3, 0xfa, 0xbb, 0xd1, 0x8b, 0xd6, 0x6c, 0xdc, 0x06, 0x53, 0x4f, 0xc4, 0x3d, 0x40,
	0xf5, 0x4e, 0xda, 0x35, 0x1f, 0x0d, 0x19, 0xbc, 0x80, 0xcc, 0x91, 0x54, 0xd5, 0x2a, 0x67, 0x33,
	0x36, 0x1f, 0xd7, 0x81, 0x75, 0xfa, 0xd6, 0x92, 0xa9, 0x56, 0x79, 0xd2, 0xeb, 0x3d, 0x13, 0xbf,
	0x0c, 0x78, 0xf9, 0xd3, 0x92, 0x69, 0x14, 0x69, 0x67, 0xb1, 0x04, 0x4e, 0x03, 0xcd, 0xd9, 0x6c,
	0x34, 0xe7, 0xc5, 0xe5, 0xa2, 0xcf, 0x8d, 0x06, 0x63, 0x5c, 0x6a, 0x67, 0x76, 0x75, 0xbc, 0x37,
	0x7d, 0x81, 0xc9, 0xfe, 0x00, 0x4e, 0x60, 0xf4, 0x49, 0xbb, 0xd0, 0xab, 0x83, 0x78, 0x0d, 0xe9,
	0x97, 0x5c, 0x6f, 0xc9, 0x77, 0xe2, 0xc5, 0xd9, 0x41, 0x4c, 0xdd, 0xfb, 0x77, 0xc9, 0x92, 0x89,
	0x02, 0x60, 0x30, 0xf0, 0x0a, 0xb2, 0x56, 0x1a, 0xa9, 0x6c, 0x9e, 0xf8, 0x8a, 0x27, 0x61, 0xf7,
	0xb9, 0x13, 0xeb, 0xe0, 0x89, 0x1b, 0x48, 0xbd, 0x80, 0x08, 0xc7, 0x5a, 0x2a, 0x0a, 0xe1, 0x1e,
	0xe3, 0x79, 0x9c, 0x3e, 0x0e, 0x51, 0xc5, 0x03, 0xa4, 0x65, 0xf7, 0x12, 0x2e, 0xe1, 0xf4, 0x91,
	0xdc, 0x93, 0x54, 0x64, 0x5b, 0xf9, 0x46, 0x16, 0xff, 0xeb, 0x0d, 0xd7, 0x9e, 0xe2, 0xe1, 0x61,
	0xc4, 0xd1, 0x6b, 0xe6, 0xff, 0xe7, 0xf6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x0d, 0x23, 0x67,
	0xae, 0x01, 0x00, 0x00,
}
